services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "4010:4010"
    volumes:
      - ./database:/app/database

  web:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
